name: 'Docs Deployment'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/docs/**'

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      deployments: write
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Bun setup'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 'Bun install'
        run: bun install

      - name: Build
        run: |
          cd apps/docs
          bunx @cloudflare/next-on-pages

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME_DOCS }}
          directory: .vercel/output/static
          branch: main
          wranglerVersion: '3'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/docs
